[build]
  command = "npm run build"
  publish = "dist"
  functions = "netlify/functions"

[dev]
  command = "npm run dev"
  port = 3000
  publish = "dist"
  framework = "vite"

# Netlify Functions 환경 변수 설정 (프로덕션용)
[build.environment]
  NOTION_API_KEY = "from_netlify_ui"
  VITE_API_MODE = "production"
  VITE_IS_NETLIFY = "true"

# 개발 환경용 환경 변수 (Netlify CLI 사용 시)
[dev.environment]
  VITE_API_MODE = "development"
  VITE_IS_NETLIFY = "false"

[[redirects]]
  from = "/api/notion/*"
  to = "/.netlify/functions/notion/:splat"
  status = 200

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200